name: smart_switch_baru
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  image_picker: ^1.1.1 #
  awesome_dialog: ^3.1.0
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  mqtt_client: ^10.8.0
  firebase_database: ^10.3.14
  flutter_switch: ^0.3.2
  syncfusion_flutter_gauges: ^24.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.0.5
  mysql1: ^0.20.0
  logging: ^1.2.0
  fl_chart: ^0.68.0
  gap: ^3.0.1
  carousel_slider: ^4.2.0
  intl: ^0.19.0
  salomon_bottom_bar: ^3.3.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  percent_indicator: ^4.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/splashscreen1.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splashscreen1.png
  android: true
  ios: true
  android_gravity: center

flutter:
  uses-material-design: true
  assets:
    - assets/
