name: smart_switch
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  firebase_auth: ^4.0.0
  firebase_database: ^10.0.0
  firebase_storage: ^11.0.0
  image_picker: ^1.1.1 #
  awesome_dialog: ^3.1.0
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.0.5
  mysql1: ^0.20.0
  mqtt_client: ^10.0.0
  logging: ^1.2.0
  fl_chart: ^0.68.0
  gap: ^3.0.1
  carousel_slider: ^4.2.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  salomon_bottom_bar: ^3.3.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  percent_indicator: ^4.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/
